sudo: required
services:
  - docker
before_install:
  - docker build -t yaowenqiang/frontend -f Dockerfile.dev .
script:
  - docker run yaowenqiang/frontend npm run test -- --coverage
    #deploy:
    #provider: elasticbeanstalk
    #region: "us-west-2"
    #app: "frontend"
    #env: "docker-env"
    #bucket_name: "my-bucet"
    #bucket_name: "my-path"
    #on:
    #    branch: master
    #access_key_id: $aws_access_key
    #secrect-access-key:
    #source: viue

         


